Vector is 1-dimensional array of number

## Vector in Numpy

In [9]:
import numpy as np

x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
# Transposing a regular 1-D array has no effect...
x_t = x.T    
print(x_t)


y = np.array([[25, 2, 5]], dtype=np.float16) # 2-D array
y_t = y.T
print(y_t.shape)
print(y_t)

z = np.zeros(3) # array of zeros

[25  2  5]
(3, 1)
[[25.]
 [ 2.]
 [ 5.]]


## Vector in PyTorch

In [11]:
import torch

x_pt = torch.tensor([25, 2, 5])

x_pt_t = x_pt.T

x_pt_t

C:\Users\benjhuang\AppData\Local\Temp\ipykernel_14684\319702923.py:5: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3575.)
  x_pt_t = x_pt.T


tensor([25,  2,  5])

## Vector in Tensroflow

In [5]:
import tensorflow as tf

x_tf = tf.Variable([25, 2, 5])