Tensor Transposition

In [6]:
import numpy as np
import tensorflow as tf

X = np.array([[25, 2], [5, 26], [3, 7]])

In [7]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [8]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>