Tensor Transposition

In [24]:
import numpy as np
import tensorflow as tf
import torch

X = np.array([[25, 2], [5, 26], [3, 7]])

In [25]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [26]:
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]])>

In [27]:
X =  torch.tensor([[3, 4], [5, 6], [7, 8]])
torch.add(torch.mul(X,2), 2)

tensor([[ 8, 10],
        [12, 14],
        [16, 18]])