## Loading the MNIST dataset in Keras

In [9]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()


In [10]:
# 60000 28x28 grayscale images
train_images.shape


(60000, 28, 28)

In [11]:
len(train_labels)


60000

In [12]:
train_labels


array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [13]:
test_images.shape


(10000, 28, 28)

In [14]:
len(test_labels)


10000

In [15]:
test_labels


array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

## The network architecture

In [16]:
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])


# The compilation step
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

# Preparing the image data
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype("float32") / 255


# Fitting the model
model.fit(train_images, train_labels, epochs=5, batch_size=128)


Epoch 1/5
469/469 [==============================] - 3s 5ms/step - loss: 0.2614 - accuracy: 0.9248
Epoch 2/5
469/469 [==============================] - 3s 5ms/step - loss: 0.1063 - accuracy: 0.9683
Epoch 3/5
469/469 [==============================] - 3s 5ms/step - loss: 0.0702 - accuracy: 0.9789
Epoch 4/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0501 - accuracy: 0.9854
Epoch 5/5
469/469 [==============================] - 3s 6ms/step - loss: 0.0376 - accuracy: 0.9888


## Prediction

In [17]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]


1/1 [==============================] - 0s 85ms/step


array([3.2174121e-08, 9.2921280e-09, 1.3003339e-06, 3.9358783e-05,
       6.1458599e-12, 3.7606016e-09, 4.0749305e-12, 9.9995840e-01,
       3.7579287e-08, 9.4010238e-07], dtype=float32)

In [18]:
predictions[0].argmax()


7

In [19]:
predictions[0][7]


0.9999584

In [20]:
test_labels[0]


7

## Evaluating the model on new data



In [21]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"test_acc: {test_acc}")


313/313 [==============================] - 1s 2ms/step - loss: 0.0713 - accuracy: 0.9778
test_acc: 0.9778000116348267
